language: python
python:
  - "3.4"
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests with coverage
script: "coverage run manage.py test"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
